version: '3'

services:
  ui:
    build:
      context: vlutter/python-training-ui
    ports:
      - "80:80"

  api:
    build:
      context: vlutter/python-training-api
    ports:
      - "5050:5050"
