version: '3'

services:
  ui:
    image: your_dockerhub_username/python-training-ui:latest
    ports:
      - "80:80"
    restart: always
    depends_on:
      - api

  api:
    image: your_dockerhub_username/python-training-api:latest
    ports:
      - "5000:5000"
    restart: always
