version: '3'

services:
  ui:
    image: vlutter/python-training-ui:latest
    ports:
      - "80:80"
    restart: always
    depends_on:
      - api

  api:
    image: vlutter/python-training-api:latest
    ports:
      - "5050:5050"
    restart: always
    environment:
      - DATABASE_URL=postgresql://lyubov.pan:Lisiza-3322@db:5432/python-training
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: lyubov.pan
      POSTGRES_PASSWORD: Lisiza-3322
      POSTGRES_DB: python-training
    restart: always
