version: '3'

services:
  ui:
    image: vlutter/python-training-ui:latest
    ports:
      - "80:80"
    restart: always
    depends_on:
      - api

  api:
    image: vlutter/python-training-api:latest
    ports:
      - "5050:5050"
    restart: always
